name: Deploy to Cloudflare Pages

on:
  push:
    tags:
      - '*' # 監聽所有的 tag push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare Pages
        uses: tomjschuster/cloudflare-pages-deploy-action@latest
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: astro-retypeset
